# netlify.toml

[build]
  command = "npm run build"  # Adjust according to your client-side build script
  publish = "client/public"  # Adjust according to your client-side build output directory


[[redirects]]
  # Redirect all requests to the root (except the API) to the client-side code
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  # Allow requests to the server-side API
  from = "/api/*"
  to = "localhost:5001" # Replace YOUR_SERVER_URL with the actual URL of your server
  status = 200
  force = true